version: '3.3'
services:
  backend:
    image: rotquecksilber/kupi_backend
    ports:
      - '4000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
#    env_file:
#      - ./backend/.env
    restart: unless-stopped

  frontend:
    image: rotquecksilber/kupi_frontend
    ports:
      - '8081:80'
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PGDATA=${POSTGRES_PGDATA}
#    env_file:
#      ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
