version: '3.3'

services:
  backend:
    image: rotquecksilber/kupi_backend
    ports:
      - '4000:3000'
    networks:
      - backend-network
      - frontend-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  frontend:
    image: rotquecksilber/kupi_frontend
    ports:
      - '8081:80'
    networks:
      - frontend-network
    restart: unless-stopped

  database:
    image: postgres:latest
    networks:
      - backend-network
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PGDATA=${POSTGRES_PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

networks:
  backend-network:
  frontend-network:
