import {
  AMOUNT_MORE_THEN_PRICE,
  CAN_NOT_CHANGE_PRICE,
  CANT_CHANGE_WISHLIST,
  CANT_DELETE_WISHLIST,
  EMAIL_TAKEN,
  FIRST_COPY_THE_WISH,
  NO_OFFER,
  NOT_THE_OWNER,
  OFFER_IS_HIDDEN,
  PRICE_IS_RICHED,
  USER_ALREADY_EXISTS,
  USER_NOT_FOUND,
  USERNAME_TAKEN,
  WISH_NOT_FOUND,
  WISHLIST_NOT_FOUND,
  WISHLIST_NOT_OWNED,
  WRONG_LOGIN_PASSWORD,
  YOU_ARE_THE_OWNER,
  YOU_ARE_THE_OWNER_OFFER,
} from './error-messages';
import { HttpStatus } from '@nestjs/common';

export enum ErrorCode {
  LoginOrPasswordIncorrect = 100,
  UserAlreadyExists = 101,
  UsernameTaken = 102,
  EmailTaken = 103,
  UpdateFailed = 104,
  UserNotFound = 105,
  WishNotFound = 106,
  NotTheOwner = 107,
  CanNotChangePrice = 108,
  YouAreTheOwner = 109,
  PriceIsRiched = 110,
  AmountMoreThenPrice = 111,
  YouAreTheOwnerOffer = 112,
  OfferIsHidden = 113,
  NoOffer = 114,
  CantChangeWishlist = 115,
  CantDeleteWishlist = 116,
  FirstCopyTheWish = 117,
  WishListNotFound = 118,
  WishlistNotOwned = 119,
}

export const code2message = new Map<ErrorCode, string>([
  [ErrorCode.LoginOrPasswordIncorrect, WRONG_LOGIN_PASSWORD],
  [ErrorCode.UserAlreadyExists, USER_ALREADY_EXISTS],
  [ErrorCode.UsernameTaken, USERNAME_TAKEN],
  [ErrorCode.EmailTaken, EMAIL_TAKEN],
  [ErrorCode.UserNotFound, USER_NOT_FOUND],
  [ErrorCode.WishNotFound, WISH_NOT_FOUND],
  [ErrorCode.NotTheOwner, NOT_THE_OWNER],
  [ErrorCode.CanNotChangePrice, CAN_NOT_CHANGE_PRICE],
  [ErrorCode.YouAreTheOwner, YOU_ARE_THE_OWNER],
  [ErrorCode.PriceIsRiched, PRICE_IS_RICHED],
  [ErrorCode.AmountMoreThenPrice, AMOUNT_MORE_THEN_PRICE],
  [ErrorCode.YouAreTheOwnerOffer, YOU_ARE_THE_OWNER_OFFER],
  [ErrorCode.OfferIsHidden, OFFER_IS_HIDDEN],
  [ErrorCode.NoOffer, NO_OFFER],
  [ErrorCode.CantChangeWishlist, CANT_CHANGE_WISHLIST],
  [ErrorCode.CantDeleteWishlist, CANT_DELETE_WISHLIST],
  [ErrorCode.FirstCopyTheWish, FIRST_COPY_THE_WISH],
  [ErrorCode.WishListNotFound, WISHLIST_NOT_FOUND],
  [ErrorCode.WishlistNotOwned, WISHLIST_NOT_OWNED],
]);

export const code2status = new Map<ErrorCode, HttpStatus>([
  [ErrorCode.LoginOrPasswordIncorrect, HttpStatus.UNAUTHORIZED],
  [ErrorCode.UserAlreadyExists, HttpStatus.CONFLICT],
  [ErrorCode.UsernameTaken, HttpStatus.CONFLICT],
  [ErrorCode.EmailTaken, HttpStatus.CONFLICT],
  [ErrorCode.UserNotFound, HttpStatus.NOT_FOUND],
  [ErrorCode.WishNotFound, HttpStatus.NOT_FOUND],
  [ErrorCode.NotTheOwner, HttpStatus.FORBIDDEN],
  [ErrorCode.CanNotChangePrice, HttpStatus.FORBIDDEN],
  [ErrorCode.YouAreTheOwner, HttpStatus.CONFLICT],
  [ErrorCode.PriceIsRiched, HttpStatus.CONFLICT],
  [ErrorCode.AmountMoreThenPrice, HttpStatus.CONFLICT],
  [ErrorCode.YouAreTheOwnerOffer, HttpStatus.CONFLICT],
  [ErrorCode.OfferIsHidden, HttpStatus.FORBIDDEN],
  [ErrorCode.NoOffer, HttpStatus.NOT_FOUND],
  [ErrorCode.CantChangeWishlist, HttpStatus.FORBIDDEN],
  [ErrorCode.CantDeleteWishlist, HttpStatus.FORBIDDEN],
  [ErrorCode.FirstCopyTheWish, HttpStatus.FORBIDDEN],
  [ErrorCode.WishListNotFound, HttpStatus.NOT_FOUND],
  [ErrorCode.WishlistNotOwned, HttpStatus.FORBIDDEN],
]);
